version: '3.1'

services:

  maria_db:
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"